# Generated by Django 5.2.7 on 2025-11-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
